/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reception;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author LEVY
 */
public class flog extends javax.swing.JFrame {

    /**
     * Creates new form flog
     */
    public flog() {
        initComponents();
   Dimension screenSize,frameSize;
int x,y;
screenSize=Toolkit.getDefaultToolkit().getScreenSize();
frameSize=getSize();
x=(screenSize.width-frameSize.width)/2;
y=(screenSize.height-frameSize.height)/2;
setLocation(x, y);

    CurrentDate();
        setIcon();
        lec();
    
    }
     public Void lec(){
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
         String query = "SELECT `name`FROM `visit`";
         PreparedStatement st;
         st = con.prepareStatement(query);
         ResultSet rs = st.executeQuery();
         while(rs.next()){
         disp.addItem(rs.getString("name"));
         }
   }
   catch(SQLException ex){
         Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    
    }
     
       
     
    private void setIcon() {
    
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("GLOBAL.JPG")));
    }
public void CurrentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {

                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);

                    //date.setText(day+"-"+(month+1)+"-"+(year));
                    dat.setCalendar(cal);

                    int second = cal.get(Calendar.SECOND);
                    int mint = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    // time.setText(hour+":"+(mint)+":"+(second));  

                    try {
                        sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

        clock.start();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        show = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        fac = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        cont = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dat = new com.toedter.calendar.JDateChooser();
        loc = new javax.swing.JTextField();
        disp = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        fac1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ENQUIRIES FORM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N

        show.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("FULL NAMES");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("LOCATION");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("DATE VISITED");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("GENDER");

        num.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        fac.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select School", "ICT", "LANGUAGE", "FOOD PRODUCTION", "PROFESSIONAL COURSES", "OTHER" }));
        fac.setBorder(null);
        fac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facMouseClicked(evt);
            }
        });
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        fac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cont.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        cont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("CONTACTS");

        dat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        loc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        loc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                locKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                locKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                locKeyTyped(evt);
            }
        });

        disp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        disp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View Previous Visitors" }));
        disp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("STATUS");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT REGISTERED" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("SCHOOL");

        gen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "MALE", "FEMALE" }));
        gen.setBorder(null);
        gen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genMouseClicked(evt);
            }
        });
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        gen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                genKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("COURSE");

        fac1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fac1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        fac1.setBorder(null);
        fac1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fac1MouseClicked(evt);
            }
        });
        fac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac1ActionPerformed(evt);
            }
        });
        fac1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fac1KeyPressed(evt);
            }
        });

        jButton6.setText("Refresh");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num)
                            .addComponent(cont)
                            .addComponent(gen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fac1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel2)
                                            .addGap(30, 30, 30))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fac1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(20, 20, 20)
                                .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/back-icon.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/Clear-icon.png"))); // NOI18N
        jButton5.setText("Refresh");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reception/change.jpg"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cont.requestFocus();
        }
    }//GEN-LAST:event_numKeyPressed

    private void numKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyReleased
      
    }//GEN-LAST:event_numKeyReleased

    private void facMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facMouseClicked
        //if(coz.getSelectedItem()=="ICT")
        //
        //     {
            //        try{
                //        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/global", "root", "");
                //         String query = "SELECT `name`FROM `ict";
                //         PreparedStatement st;
                //         st = con.prepareStatement(query);
                //         ResultSet rs = st.executeQuery();
                //         while(rs.next()){
                    //         coz1.addItem(rs.getString("name"));
                    //         }
                //   }
            //   catch(SQLException ex){
                //         Logger.getLogger(admit.class.getName()).log(Level.SEVERE, null, ex);
                //        }
            //
            //     }
        //     if(coz.getSelectedItem()=="ENGLISH")
        //                 {
            //            try{
                //        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/global", "root", "");
                //         String query = "SELECT `name`FROM `english";
                //         PreparedStatement st;
                //         st = con.prepareStatement(query);
                //         ResultSet rs = st.executeQuery();
                //         while(rs.next()){
                    //         coz1.addItem(rs.getString("name"));
                    //         }
                //   }
            //   catch(SQLException ex){
                //         Logger.getLogger(admit.class.getName()).log(Level.SEVERE, null, ex);
                //        }
            //
            //                 }
    }//GEN-LAST:event_facMouseClicked

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        if (fac.getSelectedItem() == "ICT") {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
                String query = "SELECT `name`FROM `ict";
                PreparedStatement st;
                st = con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    fac1.addItem(rs.getString("name"));
                      

                }
            } catch (SQLException ex) {
                Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        } else if (fac.getSelectedItem() == "LANGUAGE") {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
                String query = "SELECT `name`FROM `fl`";
                PreparedStatement st;
                st = con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    fac1.addItem(rs.getString("name"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (fac.getSelectedItem() == "FOOD PRODUCTION") {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
                String query = "SELECT `name`FROM `fp";
                PreparedStatement st;
                st = con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    fac1.addItem(rs.getString("name"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (fac.getSelectedItem() == "PROFESSIONAL COURSES") {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
                String query = "SELECT `name`FROM `pc";
                PreparedStatement st;
                st = con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    fac1.addItem(rs.getString("name"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
        else if (fac.getSelectedItem() == "OTHER") {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
                String query = "SELECT `name`FROM `coz";
                PreparedStatement st;
                st = con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    fac1.addItem(rs.getString("name"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
    }//GEN-LAST:event_facActionPerformed

    private void facKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fac1.requestFocus();
        }
    }//GEN-LAST:event_facKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(num.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);

}
else if( cont.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);

}

else if(loc.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);
}




else{ 
        
        String numm = num.getText();
       String facc = String.valueOf(fac1.getSelectedItem());
        String phn = cont.getText();
        String status =loc.getText();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String dob = dateformat.format(dat.getDate());
         String sta = String.valueOf(jComboBox1.getSelectedItem());
         String gender = String.valueOf(gen.getSelectedItem());
         String faculty = String.valueOf(fac.getSelectedItem());
        PreparedStatement st;
        try {
   
      Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String sql = "SELECT * FROM visit WHERE name= '" + num.getText() + "'";
            // java.sql.PreparedStatement st;
            st = con.prepareStatement(sql);
            //st.setString(1, user.getText());
            ResultSet rs = st.executeQuery(sql);
            if (rs.next() == true) {

                JOptionPane.showMessageDialog(null, "" + num.getText() + ", is are already registered into the System");
            flog l = new flog();
                            l.setVisible(true);
                            this.setVisible(false);
            
            }
            
           
     
            else{
                String query = "INSERT INTO  `visit`(`name`, `cont`, `fac`, `coz`, `date`, `loc`,`status`,`gen`) VALUES (?,?,?,?,?,?,?,?)";
                st = con.prepareStatement(query);
                st.setString(1, numm);
                st.setString(2, phn);
                st.setString(3, faculty);
                st.setString(4, facc);
                st.setString(5, dob);
                st.setString(6, status);
                st.setString(7, sta);
                st.setString(8, gender);
                if(st.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "New Record entered");
                        dashbod t  = new dashbod();
                    t.setVisible(true);
                    this.setVisible(false);
                }
           
        } 
        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void contKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            gen.requestFocus();
        }
    }//GEN-LAST:event_contKeyPressed

    private void contKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contKeyReleased
        cont.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (Character.isLowerCase(keyChar)) {
                    e.setKeyChar(Character.toUpperCase(keyChar));

                }
            }

        });
    }//GEN-LAST:event_contKeyReleased

    private void contKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == keyEvent.VK_DELETE))) {
            evt.consume();

        } else if (cont.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        flog t  = new flog();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dashbod d = new dashbod();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
  num.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (Character.isLowerCase(keyChar)) {
                    e.setKeyChar(Character.toUpperCase(keyChar));

                }
            }

        });    
    }//GEN-LAST:event_numKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           try{
            PreparedStatement st;
            
          Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            
                        String sql = "UPDATE `visit` SET `name`=?,`cont`=?,`fac`=?,`coz`=?,`loc`=?,`gen`=? WHERE  name = '"+disp.getSelectedItem()+"'";
                        st = con.prepareStatement(sql);
                        st.setString(1, num.getText());
                        st.setString(2, cont.getText());
                        st.setString(3, String.valueOf(fac.getSelectedItem()));
                        st.setString(4, String.valueOf(fac1.getSelectedItem()));
                        st.setString(5, loc.getText());
                        st.setString(6, String.valueOf(gen.getSelectedItem()));
                        if(st.executeUpdate()>0){
                            JOptionPane.showMessageDialog(null, "Update Successful");
                            flog l = new flog();
                            l.setVisible(true);
                            this.setVisible(false);
                        }
                       
                        con.close();
       }catch(SQLException | ClassNotFoundException ex){
                        Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
                    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispActionPerformed
              try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String query = "SELECT `name`, `cont`, `fac`,  `coz`,  `loc`,  `gen` FROM `visit` WHERE name ='" + disp.getSelectedItem() + "'";
            PreparedStatement st;
            st = con.prepareStatement(query);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                 num.setText(rs.getString("name"));
                cont.setText(rs.getString("cont"));
                fac.setSelectedItem(rs.getString("fac"));
                fac1.setSelectedItem(rs.getString("coz"));
                loc.setText(rs.getString("loc"));
                gen.setSelectedItem(rs.getString("gen"));
                
               
        } }catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dispActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try {
     
   PreparedStatement st;
      Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String sql = "SELECT * FROM reg WHERE name= '" + num.getText() + "'";
            st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
    if (rs.next() == true) {
      JFrame frame = new JFrame();   
    if (JOptionPane.showConfirmDialog(frame,"ALL RECORDS OF "+num.getText()+" WILL BE REMOVED FROM THE SYSTEM!!\nDO YOU WANT TO REMOVE THE RECORDS?","ATLAS INTERGRATED INFORMATION MANAGEMENT SYSTEM",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
             try {
            String query1 = "DELETE FROM `reg` WHERE name = '"+num.getText()+"'";
            st = con.prepareStatement(query1);

            if(st.executeUpdate()>0){
               

            }
 try {
             //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String query = "DELETE FROM `visit` WHERE name = '"+num.getText()+"'";
            st = con.prepareStatement(query);
            
            if(st.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "RECORDS SUCCESSFULLY REMOVED FROM THE SYSTEM");    
                 flog a = new flog();
                 a.setVisible(true);
                 this.setVisible(false);
             
            }
  
        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
           } 
            }
            
    else{
    
    
        JFrame frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"ALL RECORDS OF "+num.getText()+" WILL BE REMOVED FROM THE SYSTEM!!\nDO YOU WANT TO REMOVE THE RECORDS?","ATLAS INTERGRATED INFORMATION MANAGEMENT SYSTEM",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
      // PreparedStatement st;
        try {
           //  Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String query = "DELETE FROM `visit` WHERE name = '"+num.getText()+"'";
            st = con.prepareStatement(query);
            
            if(st.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "RECORDS SUCCESSFULLY REMOVED FROM THE SYSTEM");    
                 flog a = new flog();
                 a.setVisible(true);
                 this.setVisible(false);
             
            }
  
        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    
    
    
    
    
    }
    
    
    
    
    
    
 }
        
         catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
 /* 
              //  JFrame frame = new JFrame();
//        if (JOptionPane.showConfirmDialog(frame,"DO YOU WANT TO REMOVE THE STUDENT?","ATLAS INTERGRATED INFORMATION MANAGEMENT SYSTEM",
//            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        PreparedStatement st;
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String query1 = "DELETE FROM `reg` WHERE name = '"+num.getText()+"'";
            st = con.prepareStatement(query1);

            if(st.executeUpdate()>0){
//                JOptionPane.showMessageDialog(null, "Student Successfully Removed from the System");
                 flog l = new flog();
                            l.setVisible(true);
                            this.setVisible(false);

            }

        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void locKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locKeyReleased

    }//GEN-LAST:event_locKeyReleased

    private void locKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_locKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             
             
             
             
           if(num.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);

}
else if( cont.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);

}

else if(loc.getText().trim().isEmpty()){
showMessageDialog(null, "FILL ALL FIELDS BEFORE SAVING RECORDS", "ATLAS COLLEGE RECEPTION MANAGEMENT SYSTEM", ERROR_MESSAGE);
}




else{ 
        
        String numm = num.getText();
       String facc = String.valueOf(fac.getSelectedItem());
        String phn = cont.getText();
        String status =loc.getText();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String dob = dateformat.format(dat.getDate());
         String sta = String.valueOf(jComboBox1.getSelectedItem());
        PreparedStatement st;
        try {
   
      Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stok", "root", "");
            String sql = "SELECT * FROM visit WHERE name= '" + num.getText() + "'";
            // java.sql.PreparedStatement st;
            st = con.prepareStatement(sql);
            //st.setString(1, user.getText());
            ResultSet rs = st.executeQuery(sql);
            if (rs.next() == true) {

                JOptionPane.showMessageDialog(null, "" + num.getText() + ", is are already registered into the System");
            flog l = new flog();
                            l.setVisible(true);
                            this.setVisible(false);
            
            }
            
           
     
            else{
                String query = "INSERT INTO  `visit`(`name`, `cont`, `coz`, `date`, `loc`,`status`) VALUES (?,?,?,?,?,?)";
                st = con.prepareStatement(query);
                st.setString(1, numm);
                st.setString(2, phn);
                st.setString(3, facc);
                st.setString(4, dob);
                st.setString(5, status);
                st.setString(6, sta);
                if(st.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null, "New Record entered");
                        flog t  = new flog();
                    t.setVisible(true);
                    this.setVisible(false);
                }
           
        } 
        } catch (SQLException ex) {
            Logger.getLogger(flog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}  
             
             
             
             
             
         
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void genMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_genMouseClicked

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void genKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fac.requestFocus();
        }
    }//GEN-LAST:event_genKeyPressed

    private void fac1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fac1MouseClicked

    private void fac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fac1ActionPerformed

    private void fac1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fac1KeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loc.requestFocus();
        }
    }//GEN-LAST:event_fac1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     flog f = new flog();
     f.setVisible(true);
     this.setVisible(false);
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void locKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locKeyTyped
          loc.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (Character.isLowerCase(keyChar)) {
                    e.setKeyChar(Character.toUpperCase(keyChar));

                }
            }

        });
    }//GEN-LAST:event_locKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cont;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JComboBox<String> disp;
    private javax.swing.JComboBox<String> fac;
    private javax.swing.JComboBox<String> fac1;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField num;
    private javax.swing.JTextField show;
    // End of variables declaration//GEN-END:variables

    private static class keyEvent {

        private static char VK_DELETE;

        public keyEvent() {
        }
    }
}
